### ISSUE TITLE
Annualize DBH

### ISSUE THREAD

**Issue by clgiebink** [clgiebink/UT_FVS#1]
I have a DBH value for each tree from the FIADB and I have ring width values from Justin. Back calculation of DBH will be done with ring width values, starting in the same year as the DBH measurement. This means I will need a ring width value for the same year DBH was measured. There are 603 trees. This method will work with 507 trees. I have 96 trees where the last year ring width value is more than 1 year away from the year DBH was measured. For example, DBH was measured in 1993, but the last RW value is in 1988. This method will not work for those trees. What do I do with those trees?

**Comment by clgiebink** [comment]
DBH back calculation will follow FVS back calculation from Essential FVS (pg 180):

DBH0 = DBH – k * DG , where k = 1/BRATIO and DG (diameter increment inside bark) = 2 * RW

This should be easy for DF because BRATIO is a constant, 0.867. However, for ES and PP, BRATIO depends on DBH. After I back calculate DBH0, I'll have to recalculate BRATIO and k for the DBH0-1.

**Comment by clgiebink** [comment]
I'll also need to back calculate DDS to fit the regression model (ln(DDS) linearly related to ln(DBH))

DDS = 2 * DIB * DG + DG^2 , where dib = (1/k) * DBH

**Comment by rjderose** [comment]
Courtney, That is a really good question. And one we could have anticipated had I thought a little harder about it. You are right, oftentimes in the lab we don't measure the ring during the year it was measured because it may not appear to be fully complete. Totally understandable from a field sample point of view. But what to do about the dropping sample size??!!

**Comment by rjderose** [comment]
I also wonder if the DBH back-calculation methods is for a ten-year increment, or any increment? Maybe you could take the trees that don't have a ring width in the year of DBH measurement and back predict them one year, then use RW to 'double back-predict' the other nine. Sketchy, probably.

**Comment by clgiebink** [comment]
One solution for those trees is to grow them forward, instead of backward. Some trees are to pith, so could we calculate cumulative ring width + some bark value? Although, there could be problems associated with inconsistent calculations - both for model fit and for reproducibility.

**Comment by clgiebink** [comment]
Good question. DBH back-calculations could be derived from ten-year increment data. I could ask the FVS help desk about that.

I'm not quite sure how I would back predict one year without the diameter growth increment for that year.

**Comment by clgiebink** [comment]
Issue 1: calculations break down when DBH is < 1"

Solution: stop back calculation when DBH is < 1"

Issue 2: DIA from the core mount is more than 1.0 units away from the DIA from the FIADB tree table

Solution: get rid of these trees?

**Comment by clgiebink** [comment]
In the back calculation of DBH, initial diameter at breast height (DIA) from the Forest Inventory and Analysis Database (FIADB) was used, not DIA from the core mount. No filter was done if these two values were different. DIA was assigned to the year of measurement (MEASYEAR) from the FIADB and ring width (RW) was used to back calculate. If the last year of RW was one year less than MEASYEAR, DIA was assigned to one minus the year of measurement (MEASYEAR-1). If the last year of RW was two or more years less than MEASYEAR, DBH wasn't back calculated and those trees were filtered out.
