### ISSUE TITLE
Climate variables

### ISSUE THREAD

**Issue by clgiebink** [clgiebink/UT_FVS#10]
Some things to consider when fitting climate variables:

- How complicated should we get? In other words, how many variables? I think we decided to keep it simple - one precipitation term, one temperature term, and maybe an interaction.

- Is it best to choose climate variables that are going to be easy to project? Right now the models are performing better with previous October/August precipitation, but that might be hard to project and use to forecast tree growth. It might be best to choose water year.

**Comment by mekevans** [comment]
I was arguing for water year, thinking that smaller seasonal variables might experience "phenology drift"...the exact timing of when precipitation sensitivity is greatest might shift over time with changing climatic conditions...

**Comment by clgiebink** [comment]
Going to try fitting a 16-month (previous June to current September) precipitation parameter as well to include previous summer, which is strongly correlated with growth.
