### ISSUE TITLE
Solar radiation index

### ISSUE THREAD

**Issue by clgiebink** [clgiebink/UT_FVS#14]
Instead of having multiple aspect and slope parameters, the model could have one solar radiation parameter. Right now, there seems to be two ways to get this value:

1. Swift's solar radiation algorithm recommended by John: [Swift-1976-Water_Resources_Research.pdf](https://github.com/clgiebink/UT_FVS/files/4123558/Swift-1976-Water_Resources_Research.pdf)
2. Tyson Swetnam's GRASS r.sun: https://grass.osgeo.org/grass76/manuals/r.sun.html

Swift's algorithm calculates daily solar radiation, while Tyson's can calculate daily, monthly or annual. What would be best for the model? A seasonal solar radiation parameter? Maybe during the growing season? Or annual? To go from Swift's daily to a seasonal or annual, I'll have to meet with Tyson to figure out if it is simple addition or averaging.

Another problem is if the latitudes associated with the plot locations from the FIADB will be accurate enough to calculate solar radiation? If Tyson's program is straight forward, could I hand it off to John, who has accurate plot coordinates, to calculate the solar radiation?

**Comment by rjderose** [comment]
My vote would be for a seasonal parameter, and done with the actual coordinates, probably-depends on the resolution that r.sun works on. If it's 4km or bigger it won't matter. Also, I think we won't know the best one unless we calculate a couple (monthly, annual, seasonal) and try each of them.

**Comment by clgiebink** [comment]
I'm going to first try Swift. See sol_rad.R under scripts for exact calculation. I do have a couple questions regarding this calculation:

1. Since you can't get estimated solar radiation on a sloping surface (R6) without measured solar radiation on horizontal surface (R2), do I report potential solar radiation (R4)? If not, where can I get R2?
2. The paper says T should be tested to avoid calculating undefined values, but it doesn't say what to do if those values are undefined, which is the case for a lot of my trees. T = arcos(-tan(L) * tan(D)) or function 2. T will be undefined when -1 > L > 1. To get past this, should I just restrict values of L (either L1 or latitude) to -1 < L < 1?
3. Swift calculated total daily radiation. Would seasonal or annual radiation be an average across daily values? Or a total?

**Comment by clgiebink** [comment]
Can't seem to find a solution to the errors above, so instead I calculated direct radiation using the R package [solrad](https://cran.r-project.org/web/packages/solrad/solrad.pdf).
