### ISSUE TITLE
Compute and <maybe> back calculate CR

### ISSUE THREAD

**Issue by clgiebink** [clgiebink/UT_FVS#2]
I was able to obtain some Crown Ratio values from FIADB. Where there is missing values, I will have to commute crown ratio.

CR = 1/(1 + exp(X + N(0,SD))
where absolute value of (X + N(0,SD)) less than or equal to 86
N(0,SD) is random increment from normal distribution (Utah overview pg 11)

What is X??

**Comment by clgiebink** [comment]
I don't think I can back calculate CR. There is an equation for predicting CR (Utah overview pg 12), using Weibull-base crown model, but that won't go backward, correct?

**Comment by rjderose** [comment]
Hi Courtney,
This is my first attempt at github. So, I'll try to be helpful here. The two papers that came to mind when you mentioned crown ration are Dixon (1985) and Holdaway (1986). My guess is Utah is using the Dixon model, which has a predictor for tree crown ratio based on density, or relative density, which would be the X (in Holdaway it is DBH and BA). to back-predict you would simply need to know the back-predicted X, first, then you could back predict CR. 
[Holdaway_crownratio_86.pdf](https://github.com/clgiebink/UT_FVS/files/3056022/Holdaway_crownratio_86.pdf)
[Dixon_LCR_mod_85.pdf](https://github.com/clgiebink/UT_FVS/files/3056023/Dixon_LCR_mod_85.pdf)

Let me know if this helps. 
Justin

**Comment by clgiebink** [comment]
Thanks! I'll look into the papers. I suppose I would have to calculate stand density (X) because I'm not getting any data from the FIADB. Do you know the currently accepted way to calculate SDI? Reineke's SDI? I see John wrote about it in 2006.

**Comment by rjderose** [comment]
Courtney,
Yes, you should use the summation method for SDI. It's in John' 2000 paper (attached). 
[Shaw_SDI_00.pdf](https://github.com/clgiebink/UT_FVS/files/3069935/Shaw_SDI_00.pdf)

**Comment by clgiebink** [comment]
From Mark Castle, Biometrician, FVS (markcastle@fs.fed.us)
You can impute missing crown ratio values using the methodology proposed in the Utah variant overview. I would however exercise some caution with the imputation depending on how many missing CR observations you have. Issues with collinearity can arise since you are predicting CR from another variable. I encountered this when fitting diameter increment equations for Alaska – when I used imputed crown ratio values in the equation fitting, the signs of some coefficients switched (I believe for BAL and relative density – they became positive when they should have been negative). I would recommend fitting an equation with and without imputed crown ratio values and compare results.

**Comment by clgiebink** [comment]
I see now that I misunderstood the first equation. The first equation is only for trees where dbh is <1". For trees where dbh > 1", I use these equations:

(1) ACR = d0 +d1 +RELSDI * 100
(2) Weibull parameters:
      A = a0
      B = bo + b1 * ACR (B>=1)
      C = co + c1 * ACR (C>=2)
(3) Y = 1 - exp (-((X-A)/B))^C
(4) SCALE = 1 - 0.00167 * (CCF - 100)

First, I will estimate average stand crown ratio from relative stand density (eq 1). Then, I will estimate Weibull parameters (eq 2). Then I will create the Weibull distribution, which is based on Y multiplied by SCALE (eq 3 & 4).  Individual tree crown ratios is set from the Weibull distribution.

I'm having trouble understanding this. How do I create the distribution? Is it a normal distribution with a mean of ACR and a standard deviation of Y*SCALE? How do I pick from the distribution (rnorm(1, ACR, Y*SCALE))?

**Comment by clgiebink** [comment]
With code from Mark Castle, equation from above can be updated:

(1) ACR = d0 +d1 +RELSDI * 100
RELSDI = SDI/SDIMax
SDI from above paper (Shaw)
SDIMax from UT variant guide
(2) Weibull parameters:
A = a0
B = bo + b1 * ACR (B>=1)
C = co + c1 * ACR (C>=2)
a0-c1 from UT variant guide
(3) SCALE = 1 - 0.00167 * (CCF - 100)
(4) Y = tree rank based on DBH/total number of trees * SCALE
(5) Y = 1 - exp (-((X-A)/B))^C, but solve for X, which is CR/10
X = A + B*(-1*log(1-Y))^(1/C)
CR = X*10

**Comment by clgiebink** [comment]
Estimating crown ratio using he Weibull distribution still isn't the best method to use. To validate the calculation, I've estimated crown ratio for a subset of trees in the FIADB, which have uncompacted crown ratio (UNCRCD). Trees are selected using requirements for validation: live trees, undisturbed stands, and larger remeasurement. Here is crown ratio estimated with the Weibull distribution vs crown ratio in the field:
![cr_check](https://user-images.githubusercontent.com/44384832/75175539-c295ef80-56ef-11ea-927f-f3a6a5e2e75d.png)
Results of the regression CR_weib~UNCRCD are: 
#                       Estimate    Std. Error    t value   Pr(>|t|)    
#(Intercept)     70.028987   1.826586  38.339   <2e-16 ***
#  UNCRCD      -0.003219   0.022129  -0.145    0.884

**Comment by clgiebink** [comment]
I calculate SDI using the summation method (Shaw 2000; see above), where SDI = sum((Di/10)^1.6) and Di is the diameter of the ith tree on the stand.

If I have all the trees on the PLT_CN, all I have to do is sum those trees, correct? The problem is that gives me low values of SDI. When I compare SDI calculated using the summation method (Stage) to SDI given from the FIADB, it is much lower (about 100 off). Does Di need to multiplied by trees per acre (TPA_UNADJ)?

**Comment by clgiebink** [comment]
Before summing, multiply by trees per acre to get SDI (see above comment).

**Comment by clgiebink** [comment]
Current FVS uses compacted crown ratio to predicted growth.
Crown ratio change estimated with the Weibull distribution is known to be unreliable.
[Leites_2009.pdf](https://github.com/clgiebink/UT_FVS/files/4879989/Leites_2009.pdf)

Is there a better way to include crown ratio in the models over time? 
1) Keep crown ratio constant for 30 years back in time
2) Bound crown ratio change to 1 % of previous crown ratio per year

**Comment by clgiebink** [comment]
The standard CR calculation will be to estimate crown ratio change with the Weibull distribution, which is bound to a 1% change. However, if constant CR performs better in validation, it will be kept.
