### ISSUE TITLE
Compute and back calculate BAL

### ISSUE THREAD

**Issue by clgiebink** [clgiebink/UT_FVS#4]
First, compute rank of trees' DBH on plot. Then, compute basal area of each tree (in feet or meters?). Then, multiply basal area by TPA_UNADJ, which is the amount of trees per acre that tree represents on the plot? Finally, sum the basal area of trees larger than subject tree.

So BAL is per plot? So filter by PLT_CN?

**Comment by rjderose** [comment]
Hi Courtney, fortunately for you (but not the rest of the world) both FIA and FVS are inherently in 'standard' terms, so you'll have to do this work in feet-squared. It's simple DBH^2 * 0.005454, then multiply by TPA_CURR. That will give you BA per/tree/acre, then add them up. Your total should equal the BALIVE variable in the PLOT table (when the CONDPROP = 1.0, from COND table), just for a check. 

And yes, BAL is a plot-level metric, even though each tree gets its own BAL. You can filter by PLT_CN, or just use the PLOT column. In any given state there shouldn't be two plots with the same #.

**Comment by clgiebink** [comment]
I haven't been able to find TPA_CURR in the FIADB, but I did find TPA_UNADJ, TPAGROW_UNADJ, and TPAMORT_UNADJ. TPA_UNADJ is trees per acre unadjusted. The number of trees per acre that the sample tree theoretically represents based on the sample design. TPAGROW_UNADJ is growth trees per acre unadjusted. The number of growth trees per acre that the sample tree theoretically represents based on the sample design. TPAMORT_UNADJ is mortality trees per acre per year unadjusted. The number of mortality trees per acre per year that the sample tree theoretically represents based on the sample design. I though TPA_UNADJ would be right? But maybe TPAGROW_UNADJ?

I also thought I might need TPAMORT_UNADJ to back calculate density metrics? You could assume that these trees that are dead now may have been alive 10 years ago, contributing to competition. But that might be too complicated and really hard to figure out.

**Comment by rjderose** [comment]
Ahhhh, yes. I'm revealing my age.... TPA_UNADJ is what you want. There are older versions of the database where it was tpa_curr, but that was probably more than 10 years ago (it's just stuck in my head). You are right about using the mort keyword for adjusting for dead trees, which could be done in the context of two points in time measurements. I don't think we have the data to do that, so we won't go there.

**Comment by clgiebink** [comment]
I check with Mark Castle. BAL is on a plot level. FVS outputs subplot-level BAL, but growth models use plot-level BAL.
