### ISSUE TITLE
Monthly climate data

### ISSUE THREAD

**Issue by clgiebink** [clgiebink/UT_FVS#5]
NOAA: https://www7.ncdc.noaa.gov/CDO/CDODivisionalSelect.jsp#

unless I find some thing better

**Comment by rjderose** [comment]
Courtney, Have you thought about getting your climate data from the climateWNA product? It's pretty easy if you have a list of lat, long, elev.

**Comment by clgiebink** [comment]
I haven't. Thanks for the tip!

**Comment by clgiebink** [comment]
PRISM monthly total precipitation, minimum temperature and maximum temperature: http://www.prism.oregonstate.edu/historical/ (for 1895 - 1980 & recent past for later)
