### ISSUE TITLE
Response variable

### ISSUE THREAD

**Issue by clgiebink** [clgiebink/UT_FVS#8]
Current response for the large diameter growth model is ln(dds). DDS is predicted periodic change in squared inside bark diameter. Therefore, on an annual basis dds = (2*RW)^2.

For now, we will keep with the convention and predict DDS. We could also predict ring width (RW) or basal area increment (BAI). RW is a direct measurement, no transformations. BAI reduces the age effect.

**Comment by mekevans** [comment]
I think it's fine to stick with DDS as a response, and it shouldn't be too hard to use the coefficients from either a model of 1) ln(DDS) or 2) just DDS (i.e., gamma response), right?

**Comment by clgiebink** [comment]
I'm using ln(DDS), but for some cases DDS = 0 (RW is 0; missing ring), which is undefined in ln(). Instead of adding an arbitrarily small number (0.001), I replace 0 with the smallest measured ring width in the same core.

**Comment by clgiebink** [comment]
Sorry to reopen again. Fixing more issues I just found out existed.

DG = sqrt(dib^2 +dds) - dib
AND
DG = 2 * RW
So 
dds = (dib + (2*RW))^2 - dib^2.

See user's guide to the stand prognosis model.
