### ISSUE TITLE
Transform covariates: standardization and more

### ISSUE THREAD

**Issue by clgiebink** [clgiebink/UT_FVS#9]
Covariates are on different scales. I think the current large diameter growth model deals with this by transforming some of the variables - BAL/100 or CCF/100, but I'm not sure. I would have to ask the FVS biometricians about it.

I could deal with it by standardizing my covariates (mean centered and divided by SD). Although I see conflicting information about this approach.

Pros of standardization I've read/heard about:
Scales variables so easier to interpret output.
The predictors have mean 0. This makes it so the intercept term is interpreted as the expected value of Y when the predictor values are set to their means. Otherwise, the intercept is interpreted as the expected value of Yi when the predictors are set to 0, which may not be a realistic or interpretable situation (e.g. DBH, CR, CCF). 
Allows convergence of model.
Coefficients are equivalent to effect sizes - debatable apparently.

Cons:
Coefficients are not equivalent to effect sizes because standard deviation isn't the same across variables?
Can't deal with nonlinearities or interactions
https://statmodeling.stat.columbia.edu/2009/07/11/when_to_standar/

Not a great summary of my research, but something to start with at least. I think I'll go to the open stat lab to ask about standardization and effect sizes.

If I do decide to standardize, I may need to rethink some of the current FVS covariates, BAL/100 and CCF/100 in particular.

**Comment by clgiebink** [comment]
Standardization also causes some of my transformed variables to be weird, like log(DBH). With mean centered variables, half of the DBH values are below zero, causing log(DBH) to gives NA values. Rows with NA values are removed from the analysis.

The purpose of the log(DBH) is to linearize the relationship between dds ~ DBH, so it becomes log(dds) ~ log(DBH). If the data is model with a gamma distribution and a log link, could I get rid of the log(DBH)?

**Comment by mekevans** [comment]
I suggest centering and scaling your predictors and getting rid of the log transform of DBH
